services:
  postgres:
    image: postgres:16
    container_name: baba-postgres
    environment:
      POSTGRES_DB: baba_saas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - baba_postgres_data:/var/lib/postgresql/data

volumes:
  baba_postgres_data:

